# Generated by Django 5.2.4 on 2025-07-11 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0002_alter_lesson_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="course_previews/"
            ),
        ),
    ]
