# Generated by Django 5.2.4 on 2025-07-12 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0003_alter_course_preview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lesson",
            name="preview",
            field=models.ImageField(
                blank=True, null=True, upload_to="lesson_previews/"
            ),
        ),
    ]
