# Generated by Django 5.2.4 on 2025-07-29 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("education", "0006_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
